version: '3.9'

services:
  web:
    build:
      context: "./web"
      target: "dev"
    working_dir: "/web"
    volumes:
      - "./web:/web"
    ports:
      - "3000:3000"
    depends_on:
      - api

  api:
    build: "./api"
    working_dir: "/api"
    volumes:
      - "./api:/api"
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=api
      - FLASK_ENV=development
      # Default secret. See .env.template
      - API_SECRET_KEY="${API_SECRET_KEY:-68bca9381044dc2ee23aefbfd273c68ea68679a245b5f7e666f8d298696c7bf6}"
