version: '3.9'

services:
  web:
    build:
      context: "./web"
      target: "dev"
    working_dir: "/web"
    volumes:
      - "./web:/web"
    ports:
      - "3000:3000"
    depends_on:
      - api

  api:
    build: "./api"
    working_dir: "/api"
    volumes:
      - "./api:/api"
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=api
      - FLASK_ENV=development
