version: '3.9'

services:
  web:
    build: "./web"
    working_dir: "/web"
    volumes:
      - "./web:/web"
    ports:
      - "3000:3000"

  api:
    build: "./api"
    working_dir: "/api"
    volumes:
      - "./api:/api"
    ports:
      - "4000:4000"
