"""empty message

Revision ID: 69194782ab47
Revises: 29abdcf80840
Create Date: 2021-12-09 13:57:42.427579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69194782ab47'
down_revision = '29abdcf80840'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    op.drop_table('test_models')
    # ### end Alembic commands ###
