"""empty message

Revision ID: f4621224c677
Revises: 3db4fc86e042
Create Date: 2022-01-10 07:35:03.844990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4621224c677'
down_revision = '3db4fc86e042'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('src_user_id', sa.Integer(), nullable=False),
    sa.Column('dst_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dst_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['src_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follows')
    # ### end Alembic commands ###
